# Generated by Django 3.0.3 on 2020-03-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='desc',
        ),
    ]
